#pragma once
bool RfidStart();
void RfidEnd();
void processRfidCard();
bool readUart();
void executeCommand();
void setMode();
void setTime();
void resetStation();
void getStatus();
void initChip();
void getLastTeams();
void getTeamRecord();
void readCardPages();
void updateTeamMask();
void writeCardPage();
void readFlash();
void writeFlash();
void eraseTeamFlash();
void getConfig();
void setVCoeff();
void setGain();
void setChipType();
void setTeamFlashSize();
void setFlashBlockSize();
void setBtName();
void setBtPinCode();
void setBatteryLimit();
void scanTeams();
void sendBtCommand();
void getLastErrors();
void setAutoReport();
String sendCommandToBt(String, uint8_t);
void setAuth();
void setAuthPwd();
void setAuthPack();
void unlockChip();
void saveNewMask();
void clearNewMask();
uint16_t getBatteryLevel();
bool eepromwrite(uint16_t, uint8_t);
int eepromread(uint16_t);
void beep(uint8_t, uint16_t);
void errorBeepMs(uint8_t, uint16_t);
void errorBeep(uint8_t);
void init_package(uint8_t);
bool addData(uint8_t);
void sendData();
bool ntagAuth(uint8_t* pass, uint8_t* pack);
bool ntagWritePage(uint8_t*, uint8_t, bool verify, bool forceNoAuth);
bool ntagRead4pages(uint8_t);
bool ntagSetPassword(uint8_t* pass, uint8_t* pack, bool noAuth, bool readAndWrite, uint8_t authlim, uint8_t startPage);
bool ntagRemovePassword(uint8_t* pass, uint8_t* pack, bool noAuth, bool readAndWrite, uint8_t authlim, uint8_t startPage);
bool writeCheckPointToCard(uint8_t, uint32_t);
int findNewPage();
bool writeDumpToFlash(uint16_t, uint32_t, uint32_t, uint16_t);
bool eraseTeamFromFlash(uint16_t);
bool copyTeam(uint16_t, uint16_t);
bool readTeamFromFlash(uint16_t);
uint16_t refreshChipCounter();
void sendError(uint8_t, uint8_t);
void sendError(uint8_t);
void addLastTeam(uint16_t, bool);
void addLastError(uint8_t);
uint8_t crcCalc(uint8_t*, uint16_t, uint16_t);
void floatToByte(uint8_t*, float);
bool selectChipType(uint8_t);
void checkBatteryLevel();
void checkClockIsRunning();
void(*resetFunc) () = 0; // перезагрузка контроллера, declare reset function @ address 0
